
cc_library(
    name = "concurrent_queue",
    hdrs = glob(["*.h"]),
    #copts = ["-std=c++14"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_absl//absl/synchronization"
    ]
)